server:
  port: 8081
spring:
  datasource:
    username: root
    password: nlj6957!
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/test?&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
